# Generated by Django 5.2.6 on 2025-10-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_tags_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="Tag",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="blog.tag"
            ),
        ),
    ]
