# Generated by Django 5.2.6 on 2025-10-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_tags_tag_alter_tag_options_alter_post_tags"),
    ]

    operations = [
        # This migration previously attempted to replace the 'tags' field with 'Tag'.
        # After normalizing earlier migrations to use 'Tag', there's no schema change
        # required here. Keep migration as an empty operation list to preserve order.
    ]
